name: Test Manual Workflow

on:
  workflow_dispatch:
    input: 
      Environement:
        description: 'The environement i need to deploy on'
        required: true
        default: '/dev'

jobs:
  manual-job:
    runs-on: ubuntu-latest

    steps:
      - name: Exemple
        run:
          echo "Mon exemple"
          echo "Env name ${{ github.event.inputs.Environement }}"